remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme

title: Building Area Estimation
description: A web interface that outputs area of buildings in a given satellite image.

author: 
  name: Shantanu Sharma
